package com.kiroule.vaadin.demo.ui.view.orderedit;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.annotations.PropertyId;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.CheckBox;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class OrderEditViewDesign extends VerticalLayout {
    protected HorizontalLayout formAndMapContainer;
    protected HorizontalLayout reportHeader;
    protected Label orderId;
    protected Label stateLabel;
    protected OrderStateSelect state;
    @PropertyId("order.name")
    protected TextField fullName;
    @PropertyId("order.email")
    protected TextField email;
    @PropertyId("order.phone")
    protected TextField phone;
    @PropertyId("order.vehicleBrand")
    protected TextField vehicleBrand;
    @PropertyId("order.vehicleNumber")
    protected TextField vehicleNumber;
    @PropertyId("order.noSeats")
    protected TextField noSeats;
    @PropertyId("order.startPoint")
    protected TextField startPoint;
    @PropertyId("order.endPoint")
    protected TextField endPoint;
    @PropertyId("order.route")
    protected ComboBox<String> route;
    @PropertyId("order.validFrom")
    protected DateField validFrom;
    @PropertyId("order.validTo")
    protected DateField validTo;
    @PropertyId("order.isActive")
    protected CheckBox isActive;
    @PropertyId("order.inactiveStDate")
    protected DateField inactiveStDate;
    @PropertyId("order.inactiveEndDate")
    protected DateField inactiveEndDate;
    protected Button cancel;
    protected Button ok;

    public OrderEditViewDesign() {
		Design.read(this);
	}
}
