package com.kiroule.vaadin.demo.ui.view.orderedit;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.DateTimeField;
import com.vaadin.ui.CssLayout;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class OrderEditViewDesign extends VerticalLayout {
    protected HorizontalLayout formAndMapContainer;
    protected TextField fullName;
    protected TextField email;
    protected TextField phone;
    protected TextField vehicleBrand;
    protected TextField vehicleNumber;
    protected TextField noSeats;
    protected ComboBox<String> route;
    protected TextField startPoint;
    protected TextField endPoint;
    protected DateTimeField validFrom;
    protected DateField validTo;
    protected CheckBox inactive;
    protected DateField inactiveStDate;
    protected DateField inactiveEndDate;
    protected CheckBox chargeable;
    protected CssLayout cancelOkBtnLayout;
    protected Button cancel;
    protected Button ok;

    public OrderEditViewDesign() {
		Design.read(this);
	}
}
